<?php declare(strict_types=1);
require __DIR__ . '/bootstrap.php';
use Phessage\OneComm\CatalogClient; use Phessage\OneComm\Plugin;
$count = 0; $assert = function ($v, $m) use (&$count): void { $count++; if (!$v) throw new RuntimeException($m); };
$response = static fn (array $body, int $status = 200): array => ['response' => ['code' => $status], 'body' => json_encode($body, JSON_THROW_ON_ERROR)];
$uuid = '11111111-1111-4111-8111-111111111111'; $item = '22222222-2222-4222-8222-222222222222'; $choice = '33333333-3333-4333-8333-333333333333'; $token = 'hc_' . str_repeat('a', 43);
$client = new CatalogClient('https://sandbox.test', 'pk_test_demo');
$GLOBALS['remote'] = $response(['data' => [['id' => $uuid, 'name' => '<Pack>', 'description' => 'Trail & camp', 'available' => true, 'price' => ['amount' => '9.00', 'currency' => 'USD']]]]);
$assert(count($client->products(999)) === 1, 'catalog failed'); $assert(str_ends_with($GLOBALS['requests'][0][0], '/v1/headless/products?limit=100'), 'catalog route failed'); $assert($GLOBALS['requests'][0][1]['redirection'] === 0, 'redirect enabled');
$GLOBALS['remote'] = $response(['cartToken' => $token, 'data' => ['items' => []]], 201); $assert($client->createCart()['cartToken'] === $token, 'create failed');
$last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])]; $assert($last[1]['method'] === 'POST' && !isset($last[1]['headers']['x-cart-token']), 'create contract failed');
$GLOBALS['remote'] = $response(['data' => ['items' => [['id' => $item]]]]); $client->addItem($token, $uuid, 2); $last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])];
$assert(json_decode($last[1]['body'], true) === ['productId' => $uuid, 'quantity' => 2], 'add body failed'); $assert($last[1]['headers']['x-cart-token'] === $token, 'token missing');
$client->updateItem($token, $item, 3); $last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])]; $assert($last[1]['method'] === 'PATCH' && str_ends_with($last[0], '/items/' . $item), 'update failed');
$client->removeItem($token, $item); $last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])]; $assert($last[1]['method'] === 'DELETE' && !isset($last[1]['body']), 'remove failed');
$details = ['customerInfo' => ['email' => 'shopper@example.test']]; $client->updateCheckout($token, $details); $last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])]; $assert(json_decode($last[1]['body'], true) === $details, 'details failed');
$client->selectShippingMethod($token, $choice); $last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])]; $assert(str_ends_with($last[0], '/shipping-method') && $last[1]['method'] === 'PUT', 'shipping failed');
$client->selectPaymentMethod($token, $choice); $last = $GLOBALS['requests'][array_key_last($GLOBALS['requests'])]; $assert(str_ends_with($last[0], '/payment-method') && $last[1]['method'] === 'PUT', 'payment failed');
$before = count($GLOBALS['requests']); $assert($client->cart('bad-token') === [] && count($GLOBALS['requests']) === $before, 'bad token reached transport');
$assert((new CatalogClient('http://internal.test', 'pk_test'))->createCart() === [], 'non-TLS accepted'); $assert((new CatalogClient('https://sandbox.test', 'secret'))->products() === [], 'secret accepted');
$GLOBALS['options'] = ['onecomm_api_url' => 'https://sandbox.test', 'onecomm_publishable_key' => 'pk_test_demo']; $GLOBALS['transients'] = [];
$GLOBALS['remote'] = $response(['data' => [['id' => $uuid, 'name' => '<Pack>', 'description' => 'Trail & camp', 'available' => true, 'price' => ['amount' => '9.00', 'currency' => 'USD']]]]);
$html = Plugin::renderStorefront(12); $assert(str_contains($html, '&lt;Pack&gt;') && str_contains($html, 'Trail &amp; camp') && !str_contains($html, '<Pack>'), 'unsafe output');
$assert(str_contains($html, 'Add to cart') && str_contains($html, 'admin-post.php') && str_contains($html, '_wpnonce'), 'secure form missing');
echo $count . " assertions passed\n";
